### ISSUE TITLE
Confusion about scale of compute used for training

### ISSUE THREAD

**Issue by BradNeuberg** [aspiaspace/EarthPT#2]
On your web page you say you used a single 8xA100 40GB node trained for 5 days to get your results.

Is this 8 separate A100 machines, or a single A100 machine? This changes the cost estimates for what it takes to train this model significantly, and the original documentation is confusing on whether it is a single A100 machine or 8xA100 machines. Thanks!

**Comment by Smith42** [comment]
Hi Brad, this is for 8 individual A100 GPUs to train the 700M parameter model. We trained it on a DGX machine with 8 GPUs which is probably where the confusion comes from. It is probably possible to fit a smaller model on a single GPU for training too, if you change the batch size.

**Comment by robmarkcole** [comment]
@BradNeuberg this hardware is available on https://lightning.ai/

<img width="594" alt="image" src="https://github.com/aspiaspace/earthPT/assets/11855322/8c94de1e-dd01-4ba5-8018-42ab0f733f84">

**Comment by BradNeuberg** [comment]
Thanks!
